name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    # Pinning to macos-15 to avoid error from a changed macos-latest
    runs-on: macos-26
    permissions:
      pull-requests: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_26.2.app/Contents/Developer
          xcodebuild -version

      - name: Build for testing
        run: |
          xcodebuild build-for-testing \
            -project PoomsaeFlow/PoomsaeFlow.xcodeproj \
            -scheme PoomsaeFlow \
            -destination "platform=iOS Simulator,name=iPhone 17,OS=latest,arch=arm64" \
            -derivedDataPath build/DerivedData \
            -jobs 4 \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO

      - name: Run unit tests (PoomsaeFlowTests)
        run: |
          xcodebuild test-without-building \
            -project PoomsaeFlow/PoomsaeFlow.xcodeproj \
            -scheme PoomsaeFlow \
            -destination "platform=iOS Simulator,name=iPhone 17,OS=latest,arch=arm64" \
            -derivedDataPath build/DerivedData \
            -only-testing:PoomsaeFlowTests \
            -parallel-testing-enabled YES \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO

      - name: Convert coverage to lcov
        uses: maxep/xcodebuild-lcov-action@0.1.0
        with:
          derived-data-path: build/DerivedData
          target: PoomsaeFlow.app
          output-file: coverage/lcov.info

      - name: Post coverage report on PR
        if: github.event_name == 'pull_request'
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          lcov-file: coverage/lcov.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
